export const DATA_LOAD_START = 'DATA_LOAD_START'
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS'
export const DATA_LOAD_ERROR = 'DATA_LOAD_ERROR'

export const ADD_ITEM_START = 'ADD_ITEM_START'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR'

export const RENAME_ITEM_START = 'RENAME_ITEM_START'
export const RENAME_ITEM_SUCCESS = 'RENAME_ITEM_SUCCESS'
export const RENAME_ITEM_ERROR = 'RENAME_ITEM_ERROR'

export const DELETE_ITEM_START = 'DELETE_ITEM_START'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR'